"use client";

import Image from "next/image";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { ArrowUpRight, CalendarDays, MapPin, Volume2, VolumeX } from "lucide-react";
import { weddingConfig } from "@/config/wedding";
import { PremiumAtmosphere } from "@/components/invitation/PremiumAtmosphere";
import { LuxuryCountdown } from "@/components/invitation/LuxuryCountdown";
import { MandapScene } from "@/components/invitation/MandapScene";
import { CinematicGallery } from "@/components/invitation/CinematicGallery";
import { CinematicEnvelope } from "@/components/invitation/CinematicEnvelope";
import { ScratchDateReveal } from "@/components/invitation/ScratchDateReveal";
import { OccasionsSection } from "@/components/invitation/OccasionsSection";

function GoldLine(){return <span className="lux-line" aria-hidden="true"/>}
function Reveal({children,className=""}:{children:ReactNode;className?:string}){return <div className={`lux-reveal ${className}`}>{children}</div>}

export default function Page(){
 const [opened,setOpened]=useState(false),[music,setMusic]=useState(false),[language,setLanguage]=useState<"EN"|"TE">("EN");
 const [activeStar,setActiveStar]=useState(0); const audioRef=useRef<HTMLAudioElement>(null);
 useEffect(()=>{document.body.style.overflow=opened?"auto":"hidden";return()=>{document.body.style.overflow="auto"}},[opened]);
 const toggleMusic=async()=>{const a=audioRef.current;if(!a)return;if(music){a.pause();setMusic(false)}else{try{await a.play();setMusic(true)}catch{setMusic(false)}}};
 const blessings=["Dharma · a life of shared purpose","Prema · love that grows with every season","Maitri · friendship and companionship","Santosha · joy in the little moments","Sahacharya · walking together through life","Kutumba · two families becoming one","Akshaya · a bond that keeps blossoming"];
 return <div className="luxury-invitation"><PremiumAtmosphere/><audio ref={audioRef} loop preload="none" src={weddingConfig.music.source}/>{!opened&&<CinematicEnvelope onOpen={()=>setOpened(true)}/>} {opened&&<main>
  <nav className="lux-nav"><a href="#top" className="lux-nav-mark">K<span>&</span>T</a><div className="lux-nav-links"><a href="#celebrations">Occasions</a><a href="#muhurtham">Muhurtham</a><a href="#gallery">Gallery</a><a href="#venue">Venue</a></div><div className="lux-nav-actions"><button aria-label="Switch language" onClick={()=>setLanguage(language==="EN"?"TE":"EN")}>{language}</button><button aria-label="Toggle music" onClick={toggleMusic}>{music?<Volume2 size={16}/>:<VolumeX size={16}/>}</button></div></nav>
  <section id="top" className="lux-hero"><div className="lux-hero-image"><Image src={weddingConfig.couplePhoto} alt="Kavya and Tejas" fill priority sizes="100vw" className="object-cover"/></div><div className="lux-hero-overlay"/><div className="lux-hero-copy"><p className="lux-micro">WITH THE BLESSINGS OF OUR FAMILIES</p><h1>{language==="TE"?"కావ్య & తేజస్":<>Kavya <span>&</span> Tejas</>}</h1><GoldLine/><p className="lux-hero-date">27 · 08 · 2026</p><p className="lux-hero-sub">{language==="TE"?"మా కొత్త ప్రయాణానికి మిమ్మల్ని ఆహ్వానిస్తున్నాము.":"invite you to witness the beginning of forever."}</p></div><a href="#story" className="lux-scroll"><span>SCROLL TO ENTER</span></a></section>
  <ScratchDateReveal/>
  <section id="story" className="celestial-story"><div className="celestial-number">01</div><div className="celestial-noise"/><div className="celestial-copy"><p className="lux-micro gold">A CONSTELLATION OF TWO HEARTS</p><h2>Written in the stars.<br/><em>Joined by seven steps.</em></h2><p className="celestial-intro">Some promises are spoken. The most sacred ones are lived — one step, one blessing, one lifetime at a time.</p><div className="celestial-mantra"><span className="celestial-sanskrit">सखा सप्तपदा भव</span><span className="celestial-translit">Sakhā Saptapadā Bhava</span><span className="celestial-meaning">“With these seven steps, be my companion for life.”</span></div></div><div className="celestial-constellation" aria-label="Seven sacred wedding blessings">
    <div className="celestial-orbit orbit-one"/><div className="celestial-orbit orbit-two"/><div className="celestial-knot"><span>K</span><i>&amp;</i><span>T</span></div>
    {[0,1,2,3,4,5,6].map(i=><button key={i} className={`celestial-star star-${i+1} ${activeStar===i+1?"active":""}`} onClick={()=>setActiveStar(i+1)} aria-label={`Blessing ${i+1}`}><span>✦</span><b>{i+1}</b></button>)}
    <div className="celestial-blessing"><span>THE {activeStar||1}TH BLESSING</span><strong>{blessings[(activeStar||1)-1]}</strong><small>Tap another star to discover the next vow</small></div>
  </div></section>
  <LuxuryCountdown/><OccasionsSection/><section id="muhurtham"><MandapScene/></section>
  <section className="lux-statement"><div className="lux-statement-image"><Image src="/images/envelope/seq-05.jpg" alt="Wedding details" fill sizes="100vw" className="object-cover"/></div><div className="lux-statement-overlay"/><div className="lux-statement-copy"><p className="lux-micro">MARK YOUR CALENDAR</p><p className="lux-big-date">27<sup>TH</sup></p><p className="lux-month">AUGUST · 2026</p><GoldLine/><p className="lux-statement-line">Come for the celebration.<br/><em>Stay for the memories.</em></p></div></section>
  <CinematicGallery/><section id="venue" className="lux-venue lux-paper"><div className="lux-section-number">05</div><Reveal className="lux-venue-grid"><div><p className="lux-micro gold">THE DESTINATION</p><h2>Ishaar<br/><em>Staycation</em></h2><p className="lux-address">Chirravuru, Andhra Pradesh 522303<br/>India</p><a className="lux-map" href={weddingConfig.wedding.mapsUrl} target="_blank" rel="noreferrer"><MapPin size={15}/> OPEN IN MAPS <ArrowUpRight size={14}/></a></div><div className="lux-venue-card"><div className="lux-venue-card-top"><CalendarDays size={18}/><span>THURSDAY</span></div><strong>27</strong><span>AUGUST</span><span>2026</span><GoldLine/><small>ALL OCCASIONS · ONE PLACE</small></div></Reveal></section>
  <section id="rsvp" className="lux-final"><div className="lux-final-glow"/><Reveal className="lux-final-copy"><p className="lux-micro gold">WITH LOVE</p><h2>Kavya <span>&</span> Tejas</h2><p>We would be honoured to have you with us<br/>as we begin this new journey.</p><GoldLine/><p className="lux-final-date">27 · 08 · 2026</p><button className="lux-rsvp">RSVP WITH US</button></Reveal><footer>MADE WITH LOVE · KAVYA & TEJAS · 2026</footer></section>
  <style jsx global>{`
   .celestial-story{position:relative;min-height:96svh;overflow:hidden;background:radial-gradient(circle at 50% 48%,rgba(203,164,86,.12),transparent 28%),linear-gradient(180deg,#090908,#030303 80%);color:#eee5d6;display:grid;grid-template-columns:minmax(0,1fr) minmax(300px,1fr);align-items:center;gap:clamp(20px,5vw,80px);padding:clamp(90px,10vw,150px) clamp(22px,7vw,100px)}
   .celestial-number{position:absolute;top:38px;left:28px;font:500 .55rem var(--font-label);letter-spacing:.25em;color:#7d7467}.celestial-noise{position:absolute;inset:0;opacity:.18;background-image:radial-gradient(circle,#e6c77f 0 1px,transparent 1.5px);background-size:107px 121px;animation:celestialDrift 24s linear infinite}.celestial-copy{position:relative;z-index:4;max-width:600px}.celestial-copy h2{font-family:var(--font-display);font-weight:300;font-size:clamp(3rem,6vw,6rem);line-height:.9;letter-spacing:-.045em;margin:22px 0;color:#f5ead8}.celestial-copy h2 em{color:#d1aa5d;font-style:italic}.celestial-intro{max-width:520px;color:#aaa092;font-size:1rem;line-height:1.9}.celestial-mantra{margin-top:30px;padding:21px 24px;border:1px solid rgba(225,194,123,.34);background:linear-gradient(135deg,rgba(209,170,93,.11),rgba(8,8,7,.5));box-shadow:inset 0 0 35px rgba(214,174,91,.04)}.celestial-sanskrit{display:block;font-family:serif;font-size:clamp(1.5rem,3vw,2rem);color:#f1d793;text-shadow:0 0 25px rgba(240,204,112,.2)}.celestial-translit{display:block;margin-top:6px;font:500 .5rem var(--font-label);letter-spacing:.22em;text-transform:uppercase;color:#a9854d}.celestial-meaning{display:block;margin-top:10px;color:#cfc1aa;font:italic .92rem/1.5 var(--font-display)}
   .celestial-constellation{position:relative;z-index:3;width:min(42vw,520px);aspect-ratio:1;justify-self:center;display:grid;place-items:center}.celestial-orbit{position:absolute;border:1px solid rgba(218,182,103,.17);border-radius:50%;transform:rotate(-18deg)}.orbit-one{width:74%;height:42%}.orbit-two{width:58%;height:82%;transform:rotate(32deg)}.celestial-knot{position:absolute;z-index:5;width:116px;height:116px;border:1px solid rgba(235,201,122,.7);border-radius:50%;display:flex;align-items:center;justify-content:center;gap:8px;background:radial-gradient(circle,rgba(211,169,80,.18),rgba(5,5,4,.65) 65%);box-shadow:0 0 70px rgba(211,169,80,.12)}.celestial-knot span{font:300 2.1rem var(--font-display);color:#f1d38b}.celestial-knot i{font:italic 1rem var(--font-display);color:#a98342}.celestial-star{position:absolute;z-index:6;width:52px;height:52px;border:1px solid rgba(220,185,108,.3);border-radius:50%;background:rgba(8,8,7,.82);color:#caa65f;cursor:pointer;transition:.35s}.celestial-star span{font-size:1rem}.celestial-star b{display:block;font:500 .38rem var(--font-label);letter-spacing:.1em;color:#806d51}.celestial-star:hover,.celestial-star.active{transform:scale(1.16);border-color:#e4c577;box-shadow:0 0 30px rgba(227,192,105,.2);color:#f2d68e}.star-1{top:5%;left:44%}.star-2{top:20%;right:7%}.star-3{top:54%;right:1%}.star-4{bottom:8%;right:24%}.star-5{bottom:3%;left:30%}.star-6{top:55%;left:0}.star-7{top:18%;left:7%}.celestial-blessing{position:absolute;bottom:-5px;left:50%;transform:translateX(-50%);width:min(90%,430px);padding:16px 18px;text-align:center;border-top:1px solid rgba(224,191,116,.28);background:linear-gradient(180deg,transparent,rgba(5,5,4,.9))}.celestial-blessing span{display:block;font:500 .42rem var(--font-label);letter-spacing:.3em;color:#a88952}.celestial-blessing strong{display:block;margin-top:5px;font:italic 1rem var(--font-display);color:#e4d0a5}.celestial-blessing small{display:block;margin-top:6px;color:#716959;font:400 .42rem var(--font-label);letter-spacing:.16em}
   @keyframes celestialDrift{to{transform:translateY(121px)}}
   @media(max-width:760px){.celestial-story{min-height:auto;display:flex;flex-direction:column;padding:90px 18px 115px;gap:30px;text-align:center}.celestial-copy{max-width:600px}.celestial-copy h2{font-size:clamp(3rem,13vw,4.7rem)}.celestial-intro{font-size:.92rem;margin:auto}.celestial-mantra{margin-top:24px;padding:19px 15px}.celestial-constellation{width:min(92vw,500px);margin-top:5px}.celestial-knot{width:92px;height:92px}.celestial-knot span{font-size:1.65rem}.celestial-star{width:48px;height:48px}.celestial-blessing{bottom:-3px}.celestial-number{top:28px;left:18px}}
  `}</style>
 </main>}</div>;
}
